before_install:
  # Here, we decrypt a passwordless ssh key for acting as a user on the server named "travis"
  #   # See: https://docs.travis-ci.com/user/encrypting-files/#Automated-Encryption
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in _scripts/id_rsa.enc -out _scripts/id_rsa -d; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then chmod 400 _scripts/id_rsa; fi

deploy:
  # Cleanup removes keys and build artefacts.
  # See: https://docs.travis-ci.com/user/deployment/#Uploading-Files-and-skip_cleanup
  skip_cleanup: true
  provider: script
  script: bash _scripts/deploy.sh deploy _scripts/id_rsa bw1.hypha.coop 1003
  on:
    branch:
      - master

notifications:
  email: false
